# A minimal stand-in for the tdaq build system (cmake_tdaq's TDAQ.cmake), with just what the
# packages built here use. The packages keep their own CMakeLists.txt. The differences:
#   - a plain conda layout: headers in include/, libraries in lib/, executables in bin/, and
#     python modules (including the Boost.Python extensions, which python imports by their
#     library names) in TDAQ_PYTHON_DIR;
#   - externals are named as in tdaq ("ZLIB", "UUID", "Boost::python", ...) and mapped to
#     conda-forge's CMake targets here;
#   - executables marked NOINSTALL (unit tests and benchmarks) and the scripts are not built or
#     installed, nor are the executables matching TDAQ_SKIP_EXECUTABLES (test and debugging
#     programs with generic names that would clash in bin/).
include(CMakeParseArguments)
include(GNUInstallDirs)

set(TDAQ_PYTHON_DIR "${CMAKE_INSTALL_PREFIX}/lib/python" CACHE PATH
  "Where the python modules go")
set(TDAQ_SKIP_EXECUTABLES "^$" CACHE STRING "Regex of the installed executables not to build")

find_package(Threads REQUIRED)
find_package(ZLIB REQUIRED)
find_package(Boost REQUIRED CONFIG COMPONENTS headers program_options filesystem python)
find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
find_library(UUID_LIBRARY NAMES uuid REQUIRED)
find_path(UUID_INCLUDE_DIR NAMES uuid/uuid.h REQUIRED)
add_library(tdaq_uuid INTERFACE)
target_link_libraries(tdaq_uuid INTERFACE ${UUID_LIBRARY})
target_include_directories(tdaq_uuid INTERFACE ${UUID_INCLUDE_DIR})

# tdaq_set_build_flags(), for what matters for the result
set(CMAKE_INCLUDE_CURRENT_DIR ON)
add_definitions(-D_GNU_SOURCE -D_REENTRANT -D__USE_XOPEN2K8 -DBOOST_BIND_GLOBAL_PLACEHOLDERS=1)
if(CMAKE_BUILD_TYPE STREQUAL "Release")
  add_definitions(-DERS_NO_DEBUG)
endif()
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-register -fwrapv")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fwrapv")

# Map a tdaq-style list of libraries (keywords, targets of this project, external names) to
# CMake targets.
function(_tdaq_libraries result)
  set(libs)
  foreach(lib ${ARGN})
    if(lib MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$" OR TARGET ${lib} OR lib MATCHES "^-")
      list(APPEND libs ${lib})
    elseif(lib STREQUAL "ZLIB")
      list(APPEND libs ZLIB::ZLIB)
    elseif(lib STREQUAL "UUID")
      list(APPEND libs tdaq_uuid)
    elseif(lib STREQUAL "Boost")
      list(APPEND libs Boost::headers)
    elseif(lib STREQUAL "Boost::python")
      list(APPEND libs Boost::python)
    elseif(lib STREQUAL "pthread")
      list(APPEND libs Threads::Threads)
    elseif(lib STREQUAL "dl")
      list(APPEND libs ${CMAKE_DL_LIBS})
    else()
      # a target defined later in the project (targets are resolved at generation time)
      list(APPEND libs ${lib})
    endif()
  endforeach()
  set(${result} ${libs} PARENT_SCOPE)
endfunction()

function(_tdaq_sources result)
  set(srcs)
  foreach(f ${ARGN})
    if(f MATCHES "\\*")
      file(GLOB out ${f})
      list(APPEND srcs ${out})
    else()
      list(APPEND srcs ${f})
    endif()
  endforeach()
  set(${result} ${srcs} PARENT_SCOPE)
endfunction()

# Keywords without PUBLIC/PRIVATE/INTERFACE get a default one.
function(_tdaq_scoped result default)
  set(args ${ARGN})
  if(args)
    list(GET args 0 first)
    if(NOT first MATCHES "^(PUBLIC|PRIVATE|INTERFACE)$")
      list(PREPEND args ${default})
    endif()
  endif()
  set(${result} ${args} PARENT_SCOPE)
endfunction()

function(_tdaq_target_options name scope)
  cmake_parse_arguments(ARG "" "" "LINK_LIBRARIES;INCLUDE_DIRECTORIES;DEFINITIONS;OPTIONS;LINK_OPTIONS" ${ARGN})
  if(ARG_LINK_LIBRARIES)
    _tdaq_libraries(libs ${ARG_LINK_LIBRARIES})
    _tdaq_scoped(libs ${scope} ${libs})
    target_link_libraries(${name} ${libs})
  endif()
  foreach(inc ${ARG_INCLUDE_DIRECTORIES})
    if(inc STREQUAL "Boost")
      target_link_libraries(${name} ${scope} Boost::headers)
    elseif(IS_DIRECTORY ${CMAKE_SOURCE_DIR}/${inc})
      target_include_directories(${name} ${scope} $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/${inc}>)
    elseif(IS_ABSOLUTE ${inc})
      target_include_directories(${name} ${scope} ${inc})
    endif()
  endforeach()
  if(ARG_DEFINITIONS)
    _tdaq_scoped(defs ${scope} ${ARG_DEFINITIONS})
    target_compile_definitions(${name} ${defs})
  endif()
  if(ARG_OPTIONS)
    _tdaq_scoped(opts ${scope} ${ARG_OPTIONS})
    target_compile_options(${name} ${opts})
  endif()
  if(ARG_LINK_OPTIONS)
    _tdaq_scoped(opts ${scope} ${ARG_LINK_OPTIONS})
    target_link_options(${name} ${opts})
  endif()
endfunction()

function(tdaq_package)
  get_filename_component(TDAQ_PACKAGE_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME)
  message(STATUS "  ${TDAQ_PACKAGE_NAME}")
  set(TDAQ_PACKAGE_NAME ${TDAQ_PACKAGE_NAME} PARENT_SCOPE)
  add_definitions(-DTDAQ_PACKAGE_NAME=\"${TDAQ_PACKAGE_NAME}\")
  if(IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${TDAQ_PACKAGE_NAME})
    install(DIRECTORY ${TDAQ_PACKAGE_NAME} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
      FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
  endif()
endfunction()

function(tdaq_add_library name)
  cmake_parse_arguments(ARG "NOINSTALL;SHARED;STATIC;MODULE;INTERFACE" "DESTINATION"
    "LINK_LIBRARIES;INCLUDE_DIRECTORIES;DEFINITIONS;OPTIONS;LINK_OPTIONS" ${ARGN})
  set(type SHARED)
  foreach(t STATIC MODULE INTERFACE)
    if(ARG_${t})
      set(type ${t})
    endif()
  endforeach()
  _tdaq_sources(srcs ${ARG_UNPARSED_ARGUMENTS})
  add_library(${name} ${type} ${srcs})
  set(scope PUBLIC)
  if(type STREQUAL "INTERFACE")
    set(scope INTERFACE)
  endif()
  target_include_directories(${name} ${scope}
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}> $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
  _tdaq_target_options(${name} ${scope} ${ARGN})
  if(ARG_NOINSTALL)
    return()
  endif()
  # The Boost.Python extensions: python imports them by their library names.
  if(name MATCHES "^(py|erspy$)")
    install(TARGETS ${name} LIBRARY DESTINATION ${TDAQ_PYTHON_DIR})
    set_target_properties(${name} PROPERTIES INSTALL_RPATH "$ORIGIN;${CMAKE_INSTALL_PREFIX}/lib")
  else()
    install(TARGETS ${name} LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
      ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
  endif()
endfunction()

function(tdaq_add_executable name)
  cmake_parse_arguments(ARG "NOINSTALL" "OUTPUT_NAME;DESTINATION;DESCRIPTION"
    "LINK_LIBRARIES;INCLUDE_DIRECTORIES;DEFINITIONS;OPTIONS;LINK_OPTIONS;DEPENDS" ${ARGN})
  if(ARG_NOINSTALL OR name MATCHES "${TDAQ_SKIP_EXECUTABLES}")
    return()
  endif()
  _tdaq_sources(srcs ${ARG_UNPARSED_ARGUMENTS})
  add_executable(${name} ${srcs})
  _tdaq_target_options(${name} PRIVATE ${ARGN})
  install(TARGETS ${name} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endfunction()

function(tdaq_add_python_files)
  cmake_parse_arguments(ARG "" "" "DESTINATION" ${ARGN})
  file(GLOB files ${ARG_UNPARSED_ARGUMENTS})
  install(FILES ${files} DESTINATION ${TDAQ_PYTHON_DIR}/${ARG_DESTINATION})
endfunction()

function(tdaq_add_python_package name)
  cmake_parse_arguments(ARG "" "" "SOURCE" ${ARGN})
  if(NOT ARG_SOURCE)
    set(ARG_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/python)
  endif()
  install(DIRECTORY ${ARG_SOURCE}/${name} DESTINATION ${TDAQ_PYTHON_DIR}
    FILES_MATCHING PATTERN "*.py")
endfunction()

function(tdaq_add_header_directory)
  cmake_parse_arguments(ARG "" "DESTINATION" "FILES;PATTERN" ${ARGN})
  set(pattern)
  foreach(p ${ARG_FILES} ${ARG_PATTERN})
    list(APPEND pattern PATTERN ${p})
  endforeach()
  if(NOT pattern)
    set(pattern PATTERN *.h PATTERN *.hh PATTERN *.hpp)
  endif()
  foreach(d ${ARG_UNPARSED_ARGUMENTS})
    install(DIRECTORY ${d} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${ARG_DESTINATION}
      FILES_MATCHING ${pattern})
  endforeach()
endfunction()

macro(tdaq_find_python_interpreter)
endmacro()

function(tdaq_add_scripts)
endfunction()
