# Copyright (C) 2002-2024 CERN for the benefit of the ATLAS collaboration
#
# Wrapper around the configuration generated by the Gaudi build itself.
#
# ATLAS's External/Gaudi/cmake/FindGaudi.cmake (atlasexternals 2.1.91), plus a fix for
# conda-forge's gaudi package.
#

# Only find Gaudi once.
if( Gaudi_FOUND )
   return()
endif()

# Do not import the Gaudi CMake build configuration code.
set( GAUDI_NO_TOOLBOX TRUE CACHE BOOL
   "Do not use the Gaudi CMake build configuration code" )

# Decide whether to be in quiet mode.
set( _quietFlag )
if( Gaudi_FIND_QUIETLY )
   set( _quietFlag QUIET )
endif()

# Find/set up all the externals that Gaudi needs.
find_package( TBB ${_quietFlag} COMPONENTS tbb tbbmalloc tbbmalloc_proxy )
set( TBB_ROOT "${TBB_INSTALL_DIR}" CACHE PATH
   "Installation path for TBB, meant to help Gaudi" )
find_package( cppgsl ${_quietFlag} )
find_package( AIDA ${_quietFlag} )
set( AIDA_INCLUDE_DIRS "${AIDA_INCLUDE_DIRS}" CACHE PATH
   "Gaudi helper variable" )
find_package( HepPDT ${_quietFlag} )
set( HEPPDT_PDT_LIBRARY "${HEPPDT_HepPDT_LIBRARY}" CACHE FILEPATH
   "Gaudi helper variable" )
set( HEPPDT_PID_LIBRARY "${HEPPDT_HepPID_LIBRARY}" CACHE FILEPATH
   "Gaudi helper variable" )
find_package( CppUnit ${_quietFlag} )
set( CPPUNIT_LIBRARY "${CPPUNIT_cppunit_LIBRARY}" CACHE FILEPATH
   "Gaudi helper variable" )
find_package( libunwind ${_quietFlag} )
set( UNWIND_INCLUDE_DIR "${LIBUNWIND_INCLUDE_DIR}" CACHE PATH
   "Gaudi helper variable" )
string( REGEX REPLACE ".*\\$\\<BUILD_INTERFACE:([^\\>]*)\\>.*" "\\1"
   _unwindLib "${LIBUNWIND_unwind_LIBRARY}" )
set( UNWIND_LIBRARIES "${_unwindLib}" CACHE FILEPATH
   "Gaudi helper variable" )
find_package( VDT ${_quietFlag} )
mark_as_advanced( AIDA_INCLUDE_DIRS HEPPDT_PDT_LIBRARY HEPPDT_PID_LIBRARY
   CPPUNIT_LIBRARY UNWIND_INCLUDE_DIR UNWIND_LIBRARIES )

# Load Gaudi's own CMake configuration.
if( Gaudi_FIND_REQUIRED )
   set( _requiredFlag REQUIRED )
endif()
if( Gaudi_FIND_VERSIOIN_EXACT )
   set( _versionFlag EXACT )
endif()
find_package( Gaudi ${Gaudi_FIND_VERSION} ${_versionFlag} CONFIG
   ${_quietFlag} ${_requiredFlag} )

# conda-forge's gaudi (40.4) exports GaudiKernel with an absolute path to librt.so in the
# sysroot of the feedstock's build environment, which does not exist anywhere else.
if( TARGET Gaudi::GaudiKernel )
   get_target_property( _libs Gaudi::GaudiKernel INTERFACE_LINK_LIBRARIES )
   list( TRANSFORM _libs REPLACE "^/.*/sysroot/usr/lib(64)?/librt\\.(so|a)$" "rt" )
   set_target_properties( Gaudi::GaudiKernel PROPERTIES INTERFACE_LINK_LIBRARIES "${_libs}" )
   unset( _libs )
endif()

# Remove Gaudi's modules from the search path.
list( REMOVE_ITEM CMAKE_MODULE_PATH "${Gaudi_DIR}" "${Gaudi_DIR}/modules" )

# Make CMake forget that it "found" the unwind module. This is necessary because
# Gaudi's Findunwind.cmake module is terribly fragile...
get_property( _packages GLOBAL PROPERTY PACKAGES_FOUND )
list( REMOVE_ITEM _packages unwind )
set_property( GLOBAL PROPERTY PACKAGES_FOUND ${_packages} )
unset( _packages )

# Set up the GaudiKernelPkg and GaudiKernel "backwards compatibility" targets.
if( NOT TARGET "GaudiKernel" AND Gaudi_FOUND )
   add_library( GaudiKernel ALIAS Gaudi::GaudiKernel )
endif()

# Clean up.
unset( _quietFlag )
unset( TBB_ROOT )
unset( _unwindLib )
unset( CLHEP_FOUND )
unset( CLHEP_INCLUDE_DIR )
unset( CLHEP_INCLUDE_DIRS )
unset( CLHEP_LIBRARIES )

# Set some variables that make AtlasLCG set up a functional runtime environment
# for the found Gaudi installation.
if( Gaudi_FOUND )
   get_filename_component( _Gaudi_ROOT "${Gaudi_DIR}" DIRECTORY )
   get_filename_component( _Gaudi_ROOT "${_Gaudi_ROOT}" DIRECTORY )
   get_filename_component( _Gaudi_ROOT "${_Gaudi_ROOT}" DIRECTORY )
   set( GAUDI_BINARY_PATH "${Gaudi_BINARY_DIR}" )
   set( GAUDI_LIBRARY_DIRS "${Gaudi_LIBRARY_DIR}" )
   set( GAUDI_INCLUDE_DIRS "${Gaudi_INCLUDE_DIR}")
   set( GAUDI_PYTHON_PATH "${Gaudi_PYTHON_DIR}" )
   set( GAUDI_ENVIRONMENT
      PREPEND JOBOPTSEARCHPATH "${_Gaudi_ROOT}/${CMAKE_INSTALL_JOBOPTDIR}"
      PREPEND DATAPATH "${_Gaudi_ROOT}/${CMAKE_INSTALL_SHAREDIR}" )
   unset( _Gaudi_ROOT )
endif()
